site_name: RPC Kittens! Cute asyncio HTTP-RPC microservices for fun and profit
site_url: https://github.com/mailpile/kettlingar
theme:
  name: material
  palette:
    primary: amber
    accent: blue
  features:
    - content.action.edit
    - content.action.edit.link
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
